import type { QuickstartHealthScore } from "../types/index.js";
import { renderScoreCard } from "../score/Scorer.js";

export function renderMarkdownReport(score: QuickstartHealthScore): string {
  const lines: string[] = [];

  lines.push(`# FreshstartCI Report: ${score.total}/100 (Grade ${score.grade})`);
  lines.push("");
  lines.push("```text");
  lines.push(renderScoreCard(score));
  lines.push("```");
  lines.push("");
  lines.push("## Check Breakdown");
  lines.push("");
  lines.push("| Status | Check | Score | Summary |");
  lines.push("| :--- | :--- | :--- | :--- |");

  for (const check of score.checks) {
    const icon =
      check.status === "pass"
        ? "✅"
        : check.status === "warn"
          ? "⚠️"
          : check.status === "skip"
            ? "⏭️"
            : "❌";
    lines.push(
      `| ${icon} ${check.status.toUpperCase()} | ${check.name} | ${check.score}/${check.maxScore} | ${check.summary} |`,
    );
  }

  const detailsWithIssues = score.checks.filter((c) => c.details.length > 0 || c.fix !== undefined);

  if (detailsWithIssues.length > 0) {
    lines.push("");
    lines.push("## Details & Fixes");
    lines.push("");

    for (const check of detailsWithIssues) {
      lines.push(`### ${check.name}`);
      for (const d of check.details) {
        lines.push(`- **[${d.type.toUpperCase()}]** ${d.message}`);
        if (d.suggestion) {
          lines.push(`  *Suggestion:* ${d.suggestion}`);
        }
      }
      if (check.fix) {
        lines.push(`- 🛠️ **Auto-Fix Available:** ${check.fix.description}`);
      }
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(`*Report generated by FreshstartCI v${score.version} at ${score.timestamp}*`);

  return lines.join("\n");
}
